version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "${PORT}:80"
    restart: always
    env_file: .env

volumes:
  db_data: {}
  wordpress_data: {}
