version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    depends_on:
      - mariadb
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:80"
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - wordpress_network

networks:
  wordpress_network:
